### ISSUE TITLE
Displayed categories

### ISSUE THREAD

**Issue by mikeshulman** [mikeshulman/HoTT#31]
Should be useful for #22

**Comment by Alizter** [comment]
I would say this is done now?

**Comment by emilyriehl** [comment]
Yes, as of my last commit, I think more or less everything in Core.v is also in Displayed.v.
I've been meaning to start the Grothendieck construction file and wouldn't mind keeping that assignment if you're not impatient. I'll try to make some headway this week.

**Comment by Alizter** [comment]
Thanks @emilyriehl ! I recently pushed a commit changing some things in Dispalyed since they broke when I made IsGraph a parameter instead of a field of Is01Cat.

**Comment by mikeshulman** [comment]
This is great, thanks Emily!  I haven't been working on or looking at the wildcats much recently because I had my time taken up with improving the modalities, but I'm hoping to get back to it soon.
