### ISSUE TITLE
Make a PR to the main library including WildCat/Square

### ISSUE THREAD

**Issue by mikeshulman** [mikeshulman/HoTT#38]
Every time I switch from the wildcat branch to the master branch, the leftover compiled `WildCat/Square.vo` gets mistakenly imported by `Cubical/DSquare` until I delete it.  Let's at least merge a change that will stop that from happening.

First we'll have to merge `master` back into `wildcat`, which will require a bit of manual work.

**Comment by Alizter** [comment]
Or we make a PR to the main library implementing the naming changes. I don't think WildCat/Square is ready to merged into the main library yet. For one, we need to agree on a naming convention.
