### ISSUE TITLE
Separated modalities

### ISSUE THREAD

**Issue by mikeshulman** [mikeshulman/HoTT#40]
I've finished the proof of CORS 2.26 (which was needed for my general-modalities version of the LES), but am having universe problems.  Right now I think that my initial attempt at defining separated modalities with a simple typeclass relating two modalities was too naive, because the resulting relation refers only to types in one universe, whereas it ought to apply to types in any universe.  I guess that means it has to be a module type (unless we want to depend on the join construction, the way CORS does, or restrict to accessible modalities).

On the plus side, I finally hacked through the universes in `O_ind_from_inO_sigma` and realized that `ReflectiveSubuniverses_to_Modalities` _can_ actually instantiate `Modalities` after all.

**Comment by mikeshulman** [comment]
See HoTT#1197

**Comment by Alizter** [comment]
Will this be solved by HoTT#1238 ?

**Comment by mikeshulman** [comment]
Yes, I think so.
